name: Test FTP Connection to cPanel

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to cPanel and List Files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: '198.187.29.26'
          username: 'admin'
          password: 'Capslock@14'
          protocol: 'ftps'
          server-dir: /public_html  # Adjust to your directory
          dry-run: true             # Enables dry run mode for testing connection
